'\" t
.\"     Title: dracut.bootup
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 03/19/2024
.\"    Manual: dracut
.\"    Source: dracut 059-210-g9bd698c8
.\"  Language: English
.\"
.TH "DRACUT\&.BOOTUP" "7" "03/19/2024" "dracut 059\-210\-g9bd698c8" "dracut"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
dracut.bootup \- boot ordering in the initramfs
.SH "DESCRIPTION"
.sp
This flow chart illustrates the ordering of the services, if systemd is used in the dracut initramfs\&.
.sp
.if n \{\
.RS 4
.\}
.nf
                                    systemd\-journal\&.socket
                                               |
                                               v
                                    dracut\-cmdline\&.service
                                               |
                                               v
                                    dracut\-pre\-udev\&.service
                                               |
                                               v
                                     systemd\-udevd\&.service
                                               |
                                               v
local\-fs\-pre\&.target                dracut\-pre\-trigger\&.service
         |                                     |
         v                                     v
 (various mounts)  (various swap  systemd\-udev\-trigger\&.service
         |           devices\&.\&.\&.)               |             (various low\-level   (various low\-level
         |               |                     |             services: seed,       API VFS mounts:
         v               v                     v             tmpfiles, random     mqueue, configfs,
  local\-fs\&.target   swap\&.target     dracut\-initqueue\&.service    sysctl, \&.\&.\&.)        debugfs, \&.\&.\&.)
         |               |                     |                    |                    |
         \e_______________|____________________ | ___________________|____________________/
                                              \e|/
                                               v
                                        sysinit\&.target
                                               |
                             _________________/|\e___________________
                            /                  |                    \e
                            |                  |                    |
                            v                  |                    v
                        (various               |              rescue\&.service
                       sockets\&.\&.\&.)             |                    |
                            |                  |                    v
                            v                  |              rescue\&.target
                     sockets\&.target            |
                            |                  |
                            \e_________________ |                                 emergency\&.service
                                              \e|                                         |
                                               v                                         v
                                         basic\&.target                             emergency\&.target
                                               |
                        ______________________/|
                       /                       |
                       |                       v
                       |            initrd\-root\-device\&.target
                       |                       |
                       |                       v
                       |            dracut\-pre\-mount\&.service
                       |                       |
                       |                       v
                       |                  sysroot\&.mount
                       |                       |
                       |                       v
                       |             initrd\-root\-fs\&.target
           (custom initrd services)            |
                       |                       v
                       |             dracut\-mount\&.service
                       |                       |
                       |                       v
                       |            initrd\-parse\-etc\&.service
                       |                       |
                       |                       v
                       |            (sysroot\-usr\&.mount and
                       |             various mounts marked
                       |               with fstab option
                       |                x\-initrd\&.mount)
                       |                       |
                       |                       v
                       |                initrd\-fs\&.target
                       \e______________________ |
                                              \e|
                                               v
                                          initrd\&.target
                                               |
                                               v
                                    dracut\-pre\-pivot\&.service
                                               |
                                               v
                                     initrd\-cleanup\&.service
                                          isolates to
                                    initrd\-switch\-root\&.target
                                               |
                                               v
                        ______________________/|
                       /                       |
                       |        initrd\-udevadm\-cleanup\-db\&.service
                       |                       |
           (custom initrd services)            |
                       |                       |
                       \e______________________ |
                                              \e|
                                               v
                                   initrd\-switch\-root\&.target
                                               |
                                               v
                                   initrd\-switch\-root\&.service
                                               |
                                               v
                                          switch\-root
.fi
.if n \{\
.RE
.\}
.SH "AUTHOR"
.sp
Harald Hoyer
.SH "SEE ALSO"
.sp
\fBdracut\fR(8) \fBbootup\fR(7)
